### Site Settings ###
title               : jordiviv.es
description         : >-
                      "Tea, food, games, hardware and software engineering."
baseurl             : "/"  
remote_theme        : https://github.com/YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji
  - jekyll-remote-theme

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Jordi Vives
  image             : https://bit.ly/2KCvgVJ
  email             : jordivives94@gmail.com
  github            : JordiVM
# instagram         : your_username
  linkedin          : jordivivesm
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# twitch            : your_username
  twitter           : JordiV94
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - LICENSE
  - "*.log"
