source 'https://rubygems.org'

group :jekyll_plugins do
  gem 'jekyll', '~> 3.9'
  gem 'jekyll-sitemap'
  gem 'jekyll-remote-theme', '~> 0.4.3'
#  gem 'jekyll-feed'
#  gem 'jekyll-seo-tag'
  gem 'jemoji'
  gem 'jekyll-sass-converter', '~> 1.5'
  gem 'sassc', '~> 2.4'
  gem 'kramdown-parser-gfm'
end
